dbt_pl:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}"
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"  # Changed 'pass' to 'password'
      port: 5432
      schema: staging
      threads: 16
      type: postgres
  target: dev