dbt_pl:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}"
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: staging
      threads: 4
      type: postgres
  target: dev
