CREATE USER admin WITH PASSWORD 'admin123';
CREATE DATABASE IF NOT EXISTS airflow;
CREATE DATABASE IF NOT EXISTS premier_league_db;
GRANT ALL PRIVILEGES ON DATABASE airflow TO admin;
GRANT ALL PRIVILEGES ON DATABASE premier_league_db TO admin;
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;