CREATE DATABASE airflow;
CREATE DATABASE premier_league_db;

\c premier_league_db

CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS marts;

GRANT ALL PRIVILEGES ON SCHEMA raw TO admin;
GRANT ALL PRIVILEGES ON SCHEMA staging TO admin;
GRANT ALL PRIVILEGES ON SCHEMA marts TO admin;