FROM apache/airflow:2.9.1-python3.11

USER root
COPY requirements.txt /requirements.txt

USER airflow

# We chain everything into one clean RUN block using backslashes (\)
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir \
       psycopg2-binary \
       "mashumaro<3.13" \
       "dbt-postgres>=1.8.0,<1.9.0" \
       "dbt-core==1.11.11"
   #  -r /requirements.txt